#!/bin/bash

# cargo run -- --main-action CustomerCRM.Types.MainAction --module CustomerCRM/UI2 --html tests/resources/01.html --src-path ../../CustomerCRM/Purescript/rigaphoto-app/src/
cargo run -- --yaml tests/resources/ekebergvn.yaml
exit 0
